org: riveroverflows
app: meal-notify-scheduler
service: meal-notify-scheduler
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  cronHandler:
    handler: index.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0 6-11 ? * MON-FRI *)
